log_source:
  file_path: "access.log"

bruteforce_detector:
  enabled: true
  time_window_seconds: 45 
  max_attempts: 5          
  target_path: "/login.php"

# Только вкл/выкл 
sqli_detector:
  enabled: true
xss_detector:
  enabled: true
traversal_detector:
  enabled: true

reporting:
  output: "console"  # Варианты: console, file
  output_file: "report.txt"